doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Data\Migrations': '%kernel.project_dir%/src/Data/Migrations'
    enable_profiler: false
    custom_template: '%kernel.project_dir%/src/Data/Migrations/migration.tpl'
