# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session: false
    exceptions:
        App\Application\Exception\NotFoundException:
            status_code: 404
            log_level: 'debug'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
