services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Application\CommandHandler\CreateProfileCommandHandler:
        tags:
            - { name: tactician.handler, command: App\Application\Command\CreateProfileCommand, bus: command }
